id = "corz"
name = "Corz"
description = "The open source coding agent."
version = "1.14.48"
schema_version = 1
authors = ["Anomaly"]
repository = "https://github.com/anomalyco/corz"

[agent_servers.corz]
name = "Corz"
icon = "./icons/corz.svg"

[agent_servers.corz.targets.darwin-aarch64]
archive = "https://github.com/anomalyco/corz/releases/download/v1.14.48/corz-darwin-arm64.zip"
cmd = "./corz"
args = ["acp"]

[agent_servers.corz.targets.darwin-x86_64]
archive = "https://github.com/anomalyco/corz/releases/download/v1.14.48/corz-darwin-x64.zip"
cmd = "./corz"
args = ["acp"]

[agent_servers.corz.targets.linux-aarch64]
archive = "https://github.com/anomalyco/corz/releases/download/v1.14.48/corz-linux-arm64.tar.gz"
cmd = "./corz"
args = ["acp"]

[agent_servers.corz.targets.linux-x86_64]
archive = "https://github.com/anomalyco/corz/releases/download/v1.14.48/corz-linux-x64.tar.gz"
cmd = "./corz"
args = ["acp"]

[agent_servers.corz.targets.windows-x86_64]
archive = "https://github.com/anomalyco/corz/releases/download/v1.14.48/corz-windows-x64.zip"
cmd = "./corz.exe"
args = ["acp"]
